language: java
jdk:
  - oraclejdk8
sudo: false
addons:
  apt:
    packages:
      - oracle-java8-installer
install: true
script: mvn install -P pre-release -Dmaven.javadoc.skip=true -B -V

cache:
  directories:
  - "$HOME/.m2"