language: java
jdk:
  - oraclejdk8
sudo: false
addons:
  apt:
    packages:
      - oracle-java8-installer
install: true

jobs:
  include:
    - stage: build
      script: mvn clean install -P pre-release -DskipTests
    - stage: healthcheck
      script: mvn test -P pre-release -Dtest=DemoTestHealthcheck
    - stage: contrato
      script: mvn test -P pre-release -Dtest=DemoTestContrato
    - stage: aceitacao
      script: mvn test -P pre-release -Dtest=DemoTestAceitacao
    - stage: funcional
      script: mvn test -P pre-release -Dtest=DemoTestParallel

cache:
  directories:
  - "$HOME/.m2"